function suthakar (){
    var a=10;
    var b=20;
    var c=25;
console.log("arithmatic operation");

console.log(a+b+c);
console.log(a*b+c);
console.log(a-c);
console.log(b+c-a);
console.log(a*c);
console.log(a/b*c);
    console.log(a+b);
    console.log(c-b);
    console.log(b*c);
    console.log(a/b);
    console.log(a%c);
    
}
suthakar();
function operatorsdemo(){
    var a=20;
    var b=25;
    var c=a+b;
    console.log("ADDITION");
    console.log("values of A"+ a);
    console.log("values of B"+ b);
    console.log("Added A and B value"+ c);
    console.log("***************************");
    
    var c=a-b;

    console.log("**SUBTRACTION**");
    console.log("values of A"+ a);
    console.log("values of B"+ b);
    console.log("Subtract A and B value"+ c);
    console.log("***************************");

    var c=a*b;
console.log("**MULTIPICATION**");
    console.log("values of A"+ a);
    console.log("values of B"+ b);
    console.log("Multiply A and B value"+ c);
    console.log("***************************");
    var c=a/b;

    console.log("**DIVITION**");
    console.log("values of A"+ a);
    console.log("values of B"+ b);
    console.log("Divide A and B value"+ c);
    console.log("***************************");

    var c=a%b;

    console.log("**Modulus**");
    console.log("values of A"+ a);
    console.log("values of B"+ b);
    console.log("Modulos of A and B value"+ c);
    console.log("***************************");
    var c=a**b;

    console.log("**Multiple**");
    console.log("values of A"+ a);
    console.log("values of B"+ b);
    console.log("Subtract A and B value"+ c);
    console.log("***************************");
}

operatorsdemo();

function bike(){
    biketype;"Race", Model;"Yamaha",
    price;"4.7L", Speed;"300 KMPH",
}
console.log(bike.biketype)
 